\newpage
# Supplementary Table {#table}

|NIGPAS Specimen numbers|Fossil locality|Coordinates|
|--------------|--------------|-------------|
|166593, 166617|Shankou Village, Anning|24&deg;49&rsquo;53&rsquo;&rsquo;&nbsp;N, 102&deg;24&rsquo;47.9&rdquo;&nbsp;E|
|166594, 166595|Yaoying Village, Wuding|25&deg;36&rsquo;01.2&rdquo;&nbsp;N, 102&deg;20&rsquo;04.6&rdquo;&nbsp;E|
|166596--166616|Ma’anshan Village, Chengjiang|24&deg;40&rsquo;37.2&rdquo;&nbsp;N, 102&deg;58&rsquo;40.2&rdquo;&nbsp;E|


**Table S1: Provenance of fossil material.** Individuals from the Yaoying section are usually bigger, with a thicker body wall, and have a smaller ratio of apertural width to shell length than specimens from other areas. 
In the absence of other differentiating features, we consider these deviations to represent ecophenotypical variation within a single species, perhaps reflecting the increased energetics and predation pressure that accompany the shallower water depth reported at the Yaoying section [@Zhao2012].

\newpage
