---
title: "Standard (Fitch) parsimony results"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
---

# Fitch parsimony {#fitch}

Parsimony search was conducted in TNT v1.5 [@Goloboff2016] using ratchet and tree drifting heuristics [@Goloboff1999;@Nixon1999], repeating the search until the optimal score had been hit by 1500 independent searches:

> xmult:rat10 drift10 hits 1500 level 4 chklevel 5;

Searches were conducted under equal weights and results saved to file:

> piwe-; xmult; <span class="comment">/&#42; Conduct search with equal weighting &#42;/</span>
>
> tsav &#42;TNT/ew.tre;sav;tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>
>
> keep 0; hold 10000; <span class="comment">/&#42; Clear trees from memory &#42;/</span>

Further searches were conducted under extended implied weighting [@Goloboff1997;@Goloboff2014], under the concavity constants 2, 3, 4.5, 7, 10.5, 16 and 24:

> xpiwe=; <span class="comment">/&#42; Enable extended implied weighting &#42;/</span>
>
> piwe=2; xmult; <span class="comment">/&#42; Conduct analysis at k = 2 &#42;/</span>
>
> tsav &#42;TNT/xpiwe2.tre; sav; tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>
> 
> keep 0; hold 10000; <span class="comment">/&#42; Clear trees from memory &#42;/</span>
>
> piwe=3; xmult; <span class="comment">/&#42; Conduct analysis at k = 3 &#42;/</span>
>
> tsav &#42;TNT/xpiwe3.tre; sav ;tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>

We acknowledge the Willi Hennig Society for their sponsorship of the TNT software.

```{R, echo=FALSE}
tntFiles <- list.files('TNT/', pattern='xpiwe.*\\.tre', full=TRUE)
filename <- tntFiles[1]
tnTrees <- lapply(tntFiles, ReadTntTree, relativePath='.', keepEnd=1)
tnConsensi <- lapply(tnTrees, consensus)

plotPanel <- function (i) {
  ColPlot(tnConsensi[[i]])
  text(1, 0.5, paste('k =', kValues[i]), pos=4, cex=0.6)
}
```

## Implied weights

The consensus of all implied weights runs is not very well resolved. 
This lack of resolution is largely a product of a few wildcard taxa, particularly at $k = 4.5$, which obscures a consistent set of relationships between the remaining taxa:

```{R tnt-iw-consensus, echo=FALSE, fig.wid=7.1, fig.height=4}
par(mfrow=c(1, 2))
ColPlot(consensus(tnConsensi)) 
text(1, 0.5, 'Consensus of all k values', pos=4, cex=0.6)

plotPanel(1)
```
```{R tnt-iw-3-4.5, fig.width=7.1, fig.height=4, echo=FALSE}
par(mfrow=c(1, 2))
plotPanel(2)
plotPanel(3)
```

```{R tnt-iw-7-10.5, fig.width=7.1, fig.height=4, echo=FALSE}
par(mfrow=c(1, 2))
plotPanel(4)
plotPanel(5)
```

```{R tnt-iw-16-24, fig.width=7.1, fig.height=4, echo=FALSE}
par(mfrow=c(1, 2))
plotPanel(6)
plotPanel(7)
```

<!--### Consensus of all IW trees, without wildcards

Even with the anomalous results at $k = 4.5$, the essential relationships between most taxa are recovered under all weighting situations:

```{R tnt-pruned-consensus, echo=FALSE, fig.cap="TNT implied weights consensus"}
#omit <- c('Clupeafumosus_socialis', 'Micrina', 'Mickwitzia_muralensis', 'Paterimitra', 'Heliomedusa_orienta', 'Tomteluva_perturbata', 'Yuganotheca_elegans', 'Salanygolina', 'Gasconsia', 'Mummpikia_nuda')
omit <- c("none")
ColPlot(ConsensusWithout(tnConsensi, omit))
ColMissing(omit)
```
-->
\newpage

## Equal weights

```{R tnt-ew-consensus, echo=FALSE, fig.cap="TNT Equal weights consensus"}
tntEw <- list.files('TNT/', pattern='ew\\.tre', full=TRUE)
omit <- c("Micrina", "Mickwitzia_muralensis")
ColPlot(ConsensusWithout(ReadTntTree(tntEw), omit))
ColMissing(omit)
```
