---
title: "Bayesian Analysis results"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
---


# Bayesian analysis

```{R mrbayes-ini, echo=FALSE}
files <- list.files('MrBayes', pattern='^hyo\\..*\\.t$', full.names=TRUE)

allTrees <- lapply(files, read.nexus)
nTrees <- length(allTrees[[1]])

postBurnin <- lapply(allTrees, function (x) x[ceiling(nTrees * 0.1):nTrees])
```

Bayesian search was conducted in MrBayes v3.2.6 [@Ronquist2012] using the Mk model [@Lewis2001] with gamma-distributed rate variation across characters:

> lset coding=variable rates=gamma;

Branch length was drawn from a dirichlet prior distribution, which is less informative than an exponential model [@Rannala2012], but requires a prior mean tree length within about two orders of magnitude of the true value [@Zhang2012]. To satisfy this latter criterion, we specified the prior mean tree length to be equal to the length of the most parsimonious tree under equal weights, using a Dirichlet prior with $α_T = 1$, $β_T = 1/($_equal weights tree length_$/$_number of characters_$)$, $α = c = 1$:

> prset brlenspr = unconstrained: gammadir(1, `r signif(attr(my_data, 'nr')/Fitch(ew.trees[[1]], my_data), 2)`, 1, 1);

Neomorphic and transformational characters [_sensu_ @Sereno2007] were allocated to two separate partitions whose proportion of invariant characters and gamma shape parameters were allowed to vary independently:

> charset Neomorphic = `r paste(which(neomorphic), collapse=' ')`;
>
> charset Transformational = `r paste(which(!neomorphic), collapse=' ')`;
>
>
> partition chartype = 2: Neomorphic, Transformational;
>
> set partition = chartype;
>
>
> unlink shape=(all) pinvar=(all);


Neomorphic characters were not assumed to have a symmetrical transition rate – that is, the probability of the absent → present transition was allowed to differ from that of the present → absent transition, being drawn from a uniform prior:

> prset applyto=(1) symdirihyperpr=fixed(1.0);

The rate of variation in neomorphic characters was also allowed to vary from that of transformational characters:

> prset applyto=(1) ratepr=variable;

_`r outgroup`_ was selected as an outgroup:

> outgroup `r outgroup`;

Four MrBayes runs were executed, each sampling eight chains for 5&nbsp;000&nbsp;000 generations, with samples taken every 500 generations.  The first 10% of samples were discarded as burn-in.

> mcmcp ngen=5000000 samplefreq=500 nruns=4 nchains=8 burninfrac=0.1;

A posterior tree topology was derived from the combined posterior sample of all runs.

```{R mrbayes-full-consensus, echo=FALSE, fig.cap="Bayesian analysis, posterior probability > 50%, all taxa"}
omit <- c("none")
 # 'Novocrania', 'Craniops', 'Ussunia', 'Gasconsia',
thinned <- c(lapply(postBurnin[[1]], drop.tip, omit),
             lapply(postBurnin[[2]], drop.tip, omit),
             lapply(postBurnin[[3]], drop.tip, omit),
             lapply(postBurnin[[4]], drop.tip, omit))
class(thinned) <- 'multiPhylo'
ColPlot(UnitEdges(root(consensus(thinned, p=0.5), outgroup, resolve.root=TRUE)))
#ColMissing(omit)
```

```{R mrbayes-pruned-consensus, echo=FALSE, fig.cap="Bayesian analysis, posterior probability > 50%, wildcard taxa pruned"}
omit <- c(
  'Lingulosacculus', 'Mummpikia_nuda', 'Lingulellotreta_malongensis', 
  'Clupeafumosus_socialis', #'Siphonobolus_priscus',
  'Micrina', 'Heliomedusa_orienta', 'Mickwitzia_muralensis',
  'Tomteluva_perturbata', 'Yuganotheca_elegans',
  'Nisusia_sulcata', 'Kutorgina_chengjiangensis'
  )
thinned <- c(lapply(postBurnin[[1]], drop.tip, omit),
             lapply(postBurnin[[2]], drop.tip, omit),
             lapply(postBurnin[[3]], drop.tip, omit),
             lapply(postBurnin[[4]], drop.tip, omit))
class(thinned) <- 'multiPhylo'
rootedConsensus <- root(consensus(thinned, p=0.5), outgroup, resolve.root = TRUE)
ColPlot(UnitEdges(rootedConsensus))
ColMissing(omit)
```

Convergence was indicated by PSRF = 1.00 and an estimated sample size of > 1000 for each parameter:

```{R mrbayes-parameter-summary, fig.cap="MrBayes parameter summary", echo=FALSE, asis=TRUE}
knitr::kable(read.table ('MrBayes/hyo.nex.pstat', skip=1, header=TRUE),
             caption="MrBayes parameter estimates (.pstat file)")
```

It's interesting to note the position of _Gasconsia_, which is widely held to have an affinity with the craniid brachiopods, and is recovered in such a position using the inapplicable-safe parsimony algorithm (but not always when the standard Fitch parsimony algorithm is used). 

One possibility is that the failure of Bayesian analysis to recover this group as a clade reflects inappropriate handling of inapplicable data in the Mk model, though it is at present difficult to test this hypothesis.
