---
title: "Phylogenetic dataset"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
---

<!--\SItext-->
# Phylogenetic dataset {#dataset}

Analysis was performed on a new matrix of `r length(names(my_data)) - 1L` early brachiozoan taxa, including hyoliths, tommotiids and mickwitziids, which were coded for `r sum(attr(my_data, 'weight'))` morphological characters (`r sum(neomorphic)` neomorphic, `r sum(!neomorphic)` transformational).

_Namacalathus_ was incorporated as a `r length(names(my_data))`^th^ taxon, but preliminary results did not uphold the homology of its potentially brachiozoan-like features.  As such, we excluded it from our analysis due to its morphological distance from ingroup taxa, a likely source of long branch error.  _Dailyatia_ was instead selected as an outgroup as camenellans have been interpreted as the earliest diverging members of the Brachiozoa [@Skovsted2015Theearly;@Zhao2017].

Characters are coded following the recommendations of @Brazeau2018:

- We have employed reductive coding, using a distinct state to mark character inapplicability. Character specifications follow the structural syntax of @Sereno2007 in order to highlight ontological dependence between characters and emphasize the structure of the dataset.

- We have distinguished between neomorphic and transformational characters [sensu @Sereno2007] by reserving the token `0` to refer to the absence of a neomorphic (i.e. presence/absence) character.  The states of transformational characters (i.e. characters that describe a property of a feature) are represented by the tokens `1`, `2`, `3`, ...

- We code the absence of neomorphic ontologically dependent characters [sensu @Vogt2017] as absence, rather than inapplicability.


The complete dataset comprises `r length(my_chars)` character codings, of which `r sum(my_chars == '-')` are inapplicable and `r sum(!my_chars %in% c('-', '?'))` were neither ambiguous nor inapplicable.  The amount and quality of data that _is_ coded is more instructive than a measure of how many cells are ambiguous [@Wiens1998;@Wiens2003]. Of the `r ncol(my_chars)` characters, the number that were coded with an applicable token for each taxon is:

```{r Coded per taxon, echo=FALSE, asis=TRUE}
coded <- apply(my_chars, 1, function (x) sum(!(x %in% c('?', '-'))))
columns <- 3
roundLength <- ceiling(length(coded) / columns) * columns
padding <- rep('', roundLength - length(coded))
colStart <- ceiling(seq(1, roundLength + 1, len=columns + 1))[-(columns+1)]
colEnd <- c(colStart[-1] - 1, length(coded))
codeMat <- matrix('', ncol=columns * 2, nrow=colEnd[1])
codeMat[, seq_len(columns)* 2 - 1] <-
  c(paste0('_', gsub('_', ' ', names(coded), fixed=TRUE), '_'), padding)
codeMat[, seq_len(columns)* 2] <- c(paste0(coded, "   &nbsp;"), padding)

knitr::kable(codeMat, col.names=rep('', columns * 2))
```

The matrix can be viewed interactively and downloaded at Morphobank ([project 2800](https://morphobank.org/permalink/?P2800)). <mark>[This link will become live on publication of the paper. Referees should follow the pre-publication link to the dataset that has been provided in the main manuscript.]</mark>

A static version of the NEXUS file used to generate this supplementary information can be downloaded directly from https://raw.githubusercontent.com/ms609/hyoliths/master/`r gsub('^\\./', '', filename)` .

