---
title: "Standard (Fitch) parsimony results"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
---

# Fitch parsimony {#fitch}

Parsimony search was conducted in TNT v1.5 [@Goloboff2016] using ratchet and tree drifting heuristics [@Goloboff1999;@Nixon1999], repeating the search until the optimal score had been hit by 1500 independent searches:

> xmult:rat10 drift10 hits 1500 level 4 chklevel 5;

Searches were conducted under equal weights and results saved to file:

> piwe-; xmult; <span class="comment">/&#42; Conduct search with equal weighting &#42;/</span>
>
> tsav &#42;TNT/ew.tre;sav;tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>
>

Node support was estimated by calculating the proportion of jackknife replicates in which each group occurred, using 5000 symmetric resampling iterations, following the recommendations of @Kopuchian2010].

> var: nt; <span class="comment">/&#42; Define a variable for later use &#42;/</span>
>
> nelsen *; set nt ntrees; <span class="comment">/&#42; Generate strict consensus tree and mark for resampling &#42;/</span>
>
> ttag=; resample=sym 5000 frequency from 'nt'; <span class="comment">/&#42; Symmetric resampling; save group frequency &#42;/</span>
>
> log TNT/ew.sym; ttag &TNT/piwe2.svg; ttag/; log/; <span class="comment">/&#42; Write results to file &#42;/</span>
>
> keep 0; ttag-; hold 10000; <span class="comment">/&#42; Clear trees and resampling values from memory &#42;/</span>

Further searches were conducted under extended implied weighting [@Goloboff1997;@Goloboff2014], under the concavity constants `r paste(kValues[-length(kValues)], collapse=', ')` and `r kValues[length(kValues)]`:

> xpiwe=; <span class="comment">/&#42; Enable extended implied weighting &#42;/</span>
>
> piwe=2; xmult; <span class="comment">/&#42; Conduct analysis at k = 2 &#42;/</span>
>
> tsav &#42;TNT/xpiwe2.tre; sav; tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>
> 
> keep 0; ttag-; hold 10000; <span class="comment">/&#42; Clear memory &#42;/</span>
>
> piwe=3; xmult; <span class="comment">/&#42; Conduct analysis at k = 3 &#42;/</span>
>
> tsav &#42;TNT/xpiwe3.tre; sav ;tsav/; <span class="comment">/&#42; Save results to file &#42;/</span>


We acknowledge the Willi Hennig Society for their sponsorship of the TNT software.

<!-- "Jackknife resampling should be used rather than bootstrap resampling" -- @Simmons2011-->
## Results

```{R tnt-results-init, echo=FALSE}
tntFiles <- list.files('TNT/', pattern='xpiwe.*\\.tre', full=TRUE)
filename <- tntFiles[1]
tnTrees <- lapply(tntFiles, ReadTntTree, relativePath='.', keepEnd=1)
tnTrees <- lapply(tnTrees, as.multiPhylo)
tnTrees <- lapply(tnTrees, function (x) lapply(x, drop.tip, ignored_taxa))
tnConsensi <- lapply(tnTrees, consensus)
```

```{R tnt-iw-overview, echo=FALSE}
omit <- c("Micrina", "Micromitra",
          "Longtancunella_chengjiangensis",# "Yuganotheca_elegans",
          "Salanygolina", "Askepasma_toddense")#, "Tomteluva_perturbata")
majCon <- RootTree(ConsensusWithout(tnConsensi, omit, p=0.5), rootingTips)
ColPlot(majCon)
ColMissing(omit)

source('treeFunctions.R')
tnFlattened <- list()
for (i in seq_along(tnTrees)) {
  tnFlattened <- c(tnFlattened, tnTrees[[i]])
}
tnFlattened <- lapply(tnFlattened, drop.tip, omit)
tipIndex <- sort(tnFlattened[[1]]$tip.label)
tnSplits <- GetSplits(tnFlattened, tipIndex)

supporters <- SplitSupport(majCon, tnSplits, tipIndex)
nodelabels(paste0("\n\n", signif(supporters / length(tnFlattened), 3)),
           col=NodeColour(round(supporters / length(tnFlattened), 2)),
           adj=0, pos=2, frame='none', cex=0.75)
```

(ref:tnt-iw-results) Strict consensus of all trees recovered by TNT using Fitch parsimony with implied weighting

(ref:tnt-iw-explanation) The consensus of all implied weights runs is not very well resolved, largely due to a few wildcard taxa, particularly at $k = 4.5$, which obscures a consistent set of relationships between the remaining taxa.

```{R tnt-iw-consensus, fig.wid=7.1, fig.height=8, fig.cap="(ref:tnt-iw-results) (ref:first-panels) (ref:tnt-iw-explanation)", echo=FALSE}
par(mfrow=c(2, 2))
ColPlot(RootTree(consensus(tnConsensi), rootingTips))
text(1, 0.5, 'Consensus of all k values', pos=4, cex=0.6)

PlotPanel(tnConsensi, 1)
PlotPanel(tnConsensi, 2)
PlotPanel(tnConsensi, 3)
```

```{R tnt-iw-7-24, fig.width=7.1, fig.height=8, fig.cap="(ref:tnt-iw-results), (ref:second-panels)", echo=FALSE}
par(mfrow=c(2, 2))
PlotPanel(tnConsensi, 4)
PlotPanel(tnConsensi, 5)
PlotPanel(tnConsensi, 6)
PlotPanel(tnConsensi, 7)
```

<!--### Consensus of all IW trees, without wildcards

Even with the anomalous results at $k = 4.5$, the essential relationships between most taxa are recovered under all weighting situations:

```{R tnt-pruned-consensus, echo=FALSE, fig.cap="TNT implied weights consensus"}
#omit <- c('Clupeafumosus_socialis', 'Micrina', 'Mickwitzia_muralensis', 'Paterimitra', 'Heliomedusa_orienta', 'Tomteluva_perturbata', 'Yuganotheca_elegans', 'Salanygolina', 'Gasconsia', 'Mummpikia_nuda')
omit <- c("none")
ColPlot(ConsensusWithout(tnConsensi, omit))
ColMissing(omit)
```
-->
\newpage

(ref:tnt-ew-cons) Consensus of all trees obtained using equally weighted Fitch parsimony in TNT.  _Mickwitzia_ and _Micrina_ may equally parsimoniously be reconstructed in the basal region of the linguliform or rhynchonelliform lineages; as such, the inclusion of these taxa in the consensus tree reduces resolution.  These taxa were still included in the analysis used to generate this tree, but were removed from each MPT before the consensus was calculated in order that the relationships that are present in each tree might be more easily observed.  Node labels denote jackknife frequencies.

```{R tnt-ew-consensus, echo=FALSE, fig.cap="(ref:tnt-ew-cons)"}
# This function will be included in a future release of TreeSearch.
TNTText2Tree <- function (treeText) {
  treeText <- gsub("(\\d+)", "\\1,", treeText, perl = TRUE)
  treeText <- gsub(")(", "),(", treeText, fixed = TRUE)
  treeText <- gsub("*", ";", treeText, fixed = TRUE)
  # Return:
  read.tree(text = gsub(", )", ")", treeText, fixed = TRUE))
}

tntEw <- list.files('./TNT/', pattern='ew\\.tre', full=TRUE)
tntEwTrees <- ReadTntTree(tntEw, relativePath='.')
jackFile <- file('./TNT/ew.sym')
on.exit(close(jackFile))
jackLines <- readLines(jackFile)
jackTree <- TNTText2Tree(jackLines[3])
jackTipOrder <- order(as.integer(jackTree$tip.label) + 1L)
jackNodeOrder <- unique(unlist(Ancestors(jackTree, jackTipOrder)))[-1]
nTntNode <- jackTree$Nnode

jackTree$tip.label <- tntEwTrees[[1]]$tip.label
jackScores <- trimws(gsub("ttag \\+\\d+ (.*); *", "\\1", jackLines[length(jackLines) - (nTntNode - 2L):0]))
jackFreq <- gsub("^(\\d+)/.*", "\\1", jackScores)
jackGC   <- gsub("^\\d+/(\\[?\\d+\\]?)$", "\\1", jackScores)
ColPlot(jackTree)
nodeScores <- as.integer(jackFreq[order(jackNodeOrder)])
nodelabels(paste0(c('', nodeScores), "\n"),
           col=c('black', NodeColour(nodeScores / 200L + 0.5)),
           adj=0, pos=2, frame='none', cex=0.75)

#omit <- c("Micrina", "Mickwitzia_muralensis")
#ColPlot(RootTree(ConsensusWithout(tntEwTrees, omit), rootingTips))
#ColMissing(omit)
```
