---
title: "Visualizing characters"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
---

# Character reconstructions {#reconstructions}

This page provides definitions for each of the characters in our matrix, and justifies codings in particular taxa where relevant.  Further citations for codings that are not discussed in the text can be viewed by browsing the [morphological dataset](#dataset) on MorphoBank ([project 2800](https://morphobank.org/permalink/?P2800)). <mark>This link will become live on publication of the paper. Referees should follow the pre-publication link to the dataset that has been provided in the main manuscript.</mark>

Alongside its definition, each character has been mapped onto a tree.
 `r if (knitr::is_html_output()) 'Any of the optimal trees can be selected by modifying the tree number listed above each diagram.' else 'Here, we have arbitrarily selected one most parsimonious tree obtained under implied weighting, $k = 4.5$. Other trees can be viewed in the HTML version of this document at [ms609.github.io/hyoliths](https://ms609.github.io/hyoliths/reconstructions.html).'`
Each tip is labelled according to its coding in the matrix.  These states have been used to reconstruct the condition of each internal node, using the parsimony method of @Brazeau2018 as implemented in the _Inapp_ _R_ package.

We emphasize that different trees will give different reconstructions.  The character mappings are not intended to definitively establish how each character evolved, but to help the reader quickly establish how each character has been coded, and to visualize at a glance how each character fits onto a given tree.

```{R load-the-characters, echo=FALSE, message=FALSE}
source('loadTrees.R')
if (exists('localInstance') || knitr::is_html_output()) {
  trees <- unique(allTrees)
} else if (length(iw.exist) > 1L) {
  trees <- iw.exist[[ceiling(length(iw.exist)/2L)]][1] # Single [] to keep as a list of 1 tree.
} else {
  trees <- allTrees[1]
}
tree <- trees[[1]]
tree$edge.length <- rep(1, nrow(tree$edge))
rootedTrees <- lapply(trees, RootTree, outgroupTips=c('Dentalium', 'Serpula'))

char_names <- gsub("^'(.+)'$", "\\1", colnames(my_chars))
n_char <- ncol(my_chars)
char_parts <- strsplit(char_names, ": ")
char_nesting <- vapply(char_parts, length, 0L)

taxa_names <- unique(c("Namacalathus", rownames(my_chars)))
taxa_plaintext <- gsub("_", " ", taxa_names, fixed=TRUE)
taxa_italic <- paste0("_", taxa_plaintext, "_")

index <- attr(my_data, 'index')
ci_text <- vapply(trees, function (tree) {
  fitch_consistency_index <- CI(tree, fitch_data, sitewise=TRUE)
  fitch_steps <- fitch(tree, fitch_data, site='site')[index]
  min_steps <- fitch_consistency_index * fitch_steps
  # Maximum steps is tricky to calculate, so we'll leave RI [= max-obs / max-min]
  # unless referees insist on it; neither it nor CI mean much in any case.
  fitch_retention_index <- RI(tree, fitch_data, sitewise=TRUE)
  fitch_retention_index <- ifelse(fitch_retention_index == 'NaN', 'n/a', signif(fitch_retention_index, 2))
  paste0('CI = ', signif(min_steps / FitchSteps(tree, my_data)[index], 2),
                  '; Fitch CI = ', signif(fitch_consistency_index, 2),
                  '; Fitch RI = ', fitch_retention_index)
}, character(n_char), USE.NAMES=FALSE)
```
```{R SVG-setup, echo=FALSE, results="asis"}
fileNamer <- 'Brachiopod_phylogeny_files/figure-html/tree%s-char%s.svg'
if (exists('localInstance') || knitr::is_html_output()) {
  CheckDirExists <- function (x) if (!dir.exists(x)) dir.create(x)
  CheckDirExists('_book')
  CheckDirExists('_book/Brachiopod_phylogeny_files')
  CheckDirExists('_book/Brachiopod_phylogeny_files/figure-html')
  nTree <- c(length(ew.trees), vapply(iw.trees, length, 0))
  analysisNames <- c('Equal weights', paste0(c('Implied weights, k = ', rep('IW, k = ', length(kValues) - 1L)), kValues))
  treeNames <- rep(analysisNames, nTree)
  nTrees <- sum(nTree)
  treeIndex <- vapply(allTrees,
                      function (tr1)
                        which(vapply(trees, all.equal, logical(1), tr1, 
                                     use.tip.label=TRUE, use.edge.length=FALSE)),
                      integer(1))
  
  svgWidth <- 682
  svgHeight <- 682
  treeXMargins <- c(5L, 200L)
  treeYMargins <- c(7L, 8L)
  
  n_tree <- length(trees)
  eachTree <- seq_len(n_tree)
  n_tip <- length(trees[[1]]$tip.label)
  internal <- n_tip + seq_len(n_tip - 1)
  terminal <- seq_len(n_tip)
  tipLabel <- matrix('', n_tree, n_tip)
  n_edge <- dim(tree$edge)[1]
  eachEdge <- seq_len(n_edge)
  parent <- child <- matrix(0, n_tree, n_edge)
  xStep <- nodeX <- nodeY <- vector('list', n_tree)
  yStep <- round((svgHeight - treeYMargins[2] - treeYMargins[1]) / n_tip, 1)
  textY <- 3L
  nAnalyses <- length(analysisNames)
  for (i in eachTree) {
    tree <- rootedTrees[[i]]
    tipLabel[i, ] <- tree$tip.label
    treeEdge <- tree$edge
    parent[i, ] <- treeEdge[, 1]
    child[i, ] <- treeEdge[, 2]
    ancestors <- Ancestors(tree, type='all')
    nAncestors <- vapply(ancestors, length, 1)
    xStep[[i]] <- round(seq(treeXMargins[1], to=svgWidth-treeXMargins[2],
                       len=max(nAncestors) + 1L), 1)
    nodeX[[i]] <- xStep[[i]][nAncestors + 1L]
    nodeYi <- double(length(nAncestors))
    nodeYi[child[i, child[i, ] <= n_tip]] <- seq(treeYMargins[1], svgHeight-treeYMargins[2], len=n_tip)

    for (nodeI in rev(internal)) {
      nodeYi[nodeI] <- mean(nodeYi[Children(tree, nodeI)])
    }
    nodeY[[i]] <- round(nodeYi, 1)
  }
}
```

(ref:all-changes) All character changes mapped onto a single consensus tree.  Logically coherent changes are marked in <span class="color: `r brewer[[4]][4]`;">blue</span>; logically impossible changes (which are nevertheless reconstructed by the Fitch algorithm) are marked in <span class="color: `r brewer[[4]][1]`;">red</span>.  <span class="color: `r brewer[[4]][2]`;">Orange</span> denotes nodes at which homoplasy due to additional regions is mapped.[...]

```{R all-changes, echo=FALSE, fig.height=6, fig.width=8, fig.cap="(ref:all-changes)", results="asis"}
omit <- c("Micrina", "Micromitra",
          "Longtancunella_chengjiangensis",# "Yuganotheca_elegans",
          "Salanygolina", "Askepasma_toddense")#, "Tomteluva_perturbata")
majCon <- RootTree(ConsensusWithout(tnConsensi, omit, p=0.5), rootingTips)

bifurcating <- multi2di(majCon) # Nodes inserted at random
bEdge <- bifurcating$edge
bParent <- bEdge[, 1]
bChild <- bEdge[, 2]
majTips <- majCon$tip.label
bifTips <- bifurcating$tip.label
majChars <- my_chars[majTips, ]
recons <- apply(majChars, 2, function (char) {
  inapp <- apply.reconstruction(bifurcating, char)
  isApp <- vapply(inapp$Up2, function (x) !-1 %in% x, logical(1))
  enterApp <- isApp[bChild] & !isApp[bParent]
  
  fitch <- apply.reconstruction(bifurcating, char, method='Fitch', inapplicable=1)
  # Return:
  list('changes' = inapp$changes,
       'regions' = bParent[enterApp],
       'regioncounted' = inapp$regions,
       'fitches' = fitch$changes[!fitch$changes %in% inapp$changes])
})
reconLength <- length(recons[[1]])

conTip <- length(majTips)
majSplits <- vapply(Descendants(majCon, conTip + 1:Nnode(majCon), type='tips'),
           function (tips) majTips %in% majTips[tips], logical(conTip))
bifSplits <- vapply(Descendants(bifurcating, conTip + seq_len(conTip - 1L), type='tips'),
           function (tips) bifTips %in% bifTips[tips], logical(conTip))
majNos <- apply(majSplits, 2, function (x) sum(powersOf2[x]))
bifNos <- apply(bifSplits, 2, function (x) sum(powersOf2[x]))
whichNode <- integer(length(bifNos))
bifReal <- bifNos %in% majNos
whichNode[bifReal] <- vapply(bifNos[bifReal], function (x) which(majNos == x), integer(1))
whichNode[!bifReal] <- apply(bifSplits[, !bifReal, drop=FALSE], 2, function (bifSplit) {
  extras <- colSums(majSplits[!bifSplit, ])
  parentSplits <- apply(majSplits[bifSplit, ], 2, all)
  which(parentSplits & extras == min(extras[parentSplits]))
})
whichNode <- whichNode + conTip

if (knitr::is_html_output()) {
  
  majLabels <- vapply(conTip + 1:Nnode(majCon), function (node) {
    where <- vapply(recons, function (char) vapply(char, function (x) node %in% whichNode[x - conTip], logical(1)), logical(reconLength))
    whichWhere <- apply(where, 1, which)
    ret <- unlist(lapply(whichWhere, length))
    # Return: 
    ifelse(ret == 0, '', as.character(ret))
  }, character(reconLength))

  ### Calculate node coordinates for majCon
  
  internal <- conTip + 1:Nnode(majCon)
  terminal <- seq_len(conTip)
  conLabel <- character(conTip)
  conEdge <- dim(majCon$edge)[1]
  eachConEdge <- seq_len(conEdge)
  parent <- majCon$edge[, 1]
  child  <- majCon$edge[, 2]
  
  conYStep <- round((svgHeight - treeYMargins[2] - treeYMargins[1]) / conTip, 1)
  
  ancestors <- Ancestors(majCon, type='all')
  nAncestors <- vapply(ancestors, length, 1)
  conXStep <- round(seq(treeXMargins[1], to=svgWidth-treeXMargins[2],
                     len=max(nAncestors) + 1L), 1)
  conX <- conXStep[nAncestors + 1L]
  conY <- double(length(nAncestors))
  conY[child[child <= conTip]] <- seq(treeYMargins[1] + 30, svgHeight-treeYMargins[2], len=conTip)
  
  for (nodeI in rev(internal)) {
    conY[nodeI] <- mean(conY[Children(majCon, nodeI)])
  }
  conY <- round(conY, 1)
  
  edges <- paste0('<path d="', paste0('M', conX[parent], ',', conY[parent],
                                      'V', conY[child], 'H', conX[child], 
                                      collapse=''), '" stroke="#888"></path>')
  tips <- paste0('<text x="', (conX[terminal] + 0L), 
                 '" y="', conY[terminal] + textY,
                 '" fill="', taxonColour[majTips[terminal]],
                 '" class="taxonLabel">', 
                 gsub('_', ' ', majTips[terminal], fixed=TRUE), '</text>',
                 collapse='')
  nodes <- paste0('<g transform="translate(', conX[internal] + 2L, 
                  ' ', conY[internal], ')" class="node-g" data-node="', internal, 
                  '"><text x="0" y="-1.2em" class="node"><tspan class="b42">',
                  majLabels['regions', ], '</tspan><tspan class="b44" x="0" dy="1.2em">',
                  majLabels['changes', ], '</tspan><tspan class="b41" x="0" dy="1.2em">', 
                  majLabels['fitches', ], '</tspan></text></g>', collapse='')
  conCaption <- paste0('<g transform="translate(', svgWidth - 4L, ' 0)">',
                       '<text x="0" y="0" text-anchor="end" class="stepsLabel">',
                       '<tspan x="0" dy="1.2em">',
                       '<tspan class="score b44">Blue</tspan>: ',
                       'Logically valid character transformations</tspan>', 
                       '<tspan x="0" dy="1.2em"><tspan class="score b42">Orange</tspan>: ',
                       'Applicable regions</tspan>', 
                       '<tspan x="0" dy="1.2em"><tspan class="score b41">Red</tspan>: ',
                       'Logically invalid Fitch steps</tspan>',
                       '</text></g>')
  svgSource <- paste0('<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="', 
                svgWidth, '" height="', svgHeight, '" id="conTree">',
                conCaption, tips, edges, nodes, '</svg>')
  cat(svgSource)
  
  ## Generate detail-divs
  majCaptions <- vapply(conTip + 1:Nnode(majCon), function (node) {
    where <- vapply(recons, function (char) vapply(char, function (x) node %in% whichNode[x - conTip], logical(1)), logical(reconLength))
    apply(where, 1, function (changes) {
      if (any(changes)) {
        paste0('<span class=change><span class=charNo>', which(changes), 
               '</span>', gsub("^'|'$", "", names(changes[changes]), perl=TRUE),
               '</span>', collapse='') 
      } else ''
    })
  }, character(reconLength))
  ncol <- colSums(majCaptions[c('regions', 'changes', 'fitches'), ] != '')
  cat('<div id=nodeDetails>Click a node for details of changes</div>',
      paste0('<div id=nodeDetail', internal, ' class=nddtl><div class=nddtlhdr>',
         'Steps incurred at node ', internal, ':</div>',
         ifelse(majCaptions['changes', ] == '', '', 
                paste0('<div class="tfm cl', ncol, '">', 
                       majCaptions['changes', internal - conTip], '</div>')), 
         ifelse(majCaptions['regions', ] == '', '',
                paste0('<div class="rgn cl', ncol, '">',
                       majCaptions['regions', internal - conTip], '</div>')),
         ifelse(majCaptions['fitches', ] == '', '',
                paste0('<div class="ftch cl', ncol, '">',
                       majCaptions['fitches', internal - conTip], '</div>')), 
         '</div><div style="clear: both"></div>', collapse=''))
} else {
  ColPlot(majCon)
  majLabels <- vapply(conTip + 1:Nnode(majCon), function (node) {
  where <- vapply(recons, function (char) vapply(char, function (x) node %in% whichNode[x - conTip], logical(1)), logical(reconLength))
  whichWhere <- apply(where, 1, which)
  # Return: 
  if (length(whichWhere) == 0) character(reconLength) else {
    unlist(lapply(whichWhere, paste, collapse=', '))
  }
  }, character(reconLength))
  LabelNodes(majLabels['changes', ], 4, 0)
  LabelNodes(majLabels['regions', ], 2, 1)
  LabelNodes(majLabels['fitches', ], 1, 2)
}
```
<script>
// Enable consensus tree interactions:
function showNodeNotes (e) {
  var target = e.target; // Which node triggered the click
  if (target.nodeName === 'tspan')
    $target = $(target);
    gp = $target.parent().parent();
    if (gp[0].nodeName === 'g' && gp.hasClass('node-g')) {
      nodeNumber = gp.data('node');
      $("#conTree g").removeClass("bold");
      gp.addClass("bold");
      document.getElementById('nodeDetails').style='display: none';
      $('div .nddtl').css('display', 'none');
      document.getElementById('nodeDetail' + nodeNumber).style='display: block';
  }
  return false;
}
$("#conTree").click(showNodeNotes)

// Prepare for character-by-character interactions
var latestKnownScrollY = 0,
  latestKnownY = 0,
	ticking = false;

function onScreen(e, viewTop, viewHeight) {
  var viewBottom = viewTop + viewHeight;
  var elemTop = $(e).offset().top;
  return ((elemTop <= viewBottom + 1000) && (elemTop >= viewTop - 1000));
}

function highlightTaxon (e) {
  var target = e.target; // Which node triggered the click
  $target = $(target);
  if (target.nodeName === 'text' && $target.hasClass('taxonLabel')) {
    taxonText = $(target).text();
    $withSameText = $('#reconstructions svg text:contains("' + taxonText + '")')
    if (localStorage.getItem(taxonText)) {
      localStorage.removeItem(taxonText)
      $withSameText.removeClass("highlightTaxon");
    } else {
      localStorage.setItem(taxonText, 1)
      $withSameText.addClass("highlightTaxon");
    }
  }
  return false;
}

function applyHighlighting () {
  if(localStorage.getItem($(this).text())) {
    $(this).addClass("highlightTaxon");
  }
}

function onScroll() {
  //Optimised via https://www.html5rocks.com/en/tutorials/speed/animations/
  latestKnownScrollY = window.scrollY;
  latestKnownY = $(window).height();
  requestTick();
}

function requestTick() {
  if (!ticking) {
    requestAnimationFrame(updateVisible);
  }
  ticking = true;
}

function updateVisible() {
  ticking = false; // Reset, ready to capture next scroll/resize
  chosenTree = localStorage.getItem("chosenTree");
  var currentScrollY = latestKnownScrollY;
  var currentHeight = latestKnownY;
  $("svg.tree").each(function(index, item) {
    if (onScreen($(this), currentScrollY, currentHeight)) {
      if ($(this).data('tree') != chosenTree) {        
        var oldTree = $(item);
        $.ajax({
           //url: "`r sprintf(fileNamer, '" + chosenTree + "', '" + $(oldTree).data("char") + "')`",
           url: "Brachiopod_phylogeny_files/figure-html/tree" + chosenTree + "-char" +
                $(oldTree).data("char") + ".svg",
          context: item,
          datatype: 'xml'
        }).done(function (newTree) {
          $newSvg = $('svg', newTree);
          $newSvg.data('tree', chosenTree);
          $newSvg.click(highlightTaxon);
          $('text', $newSvg).each(applyHighlighting);
          $(this).replaceWith($newSvg);
        })
      }
    }
  });
  return false;
}

function switchTree(input) {
  newValue = input.value * 1;
  if (!isNaN(newValue)) {
    newValue = Math.floor(newValue);
    newValue = Math.max(newValue, 1);
    newValue = Math.min(newValue, input.max);
    $("input.switcherNumber").val(newValue);
    localStorage.setItem("chosenTree", newValue);
    updateVisible()
  }
  return false;
}


$(document).ready(function() {
  window.$my = {
    trees : $("svg.tree")
  };

  // Produce switcher box by each SVG plot
  var originalSwitcher = $("div.switcher");
  $my.trees.each(function() {
      var thisTree = $(this);
      var switcherClone = originalSwitcher.clone().insertBefore(thisTree);
      $('input.switcherNumber', switcherClone).data("char", thisTree.data("char"));
    }
  );
  
  localStorage.setItem("chosenTree", originalSwitcher.val());
  $my.trees.click(highlightTaxon)
  $my.trees.data('tree', originalSwitcher.val());
  $('text', $my.trees).each(applyHighlighting)
  
  $(".book-body").scroll(onScroll);
  $(".book-body").resize(onScroll);
  
  $(".body-inner").resize(onScroll);
  $(".body-inner").scroll(onScroll);
  // page-wrapper and page-inner are the other things that might trigger events?
  
  originalSwitcher.remove();
  return false;
});
</script>
```{R character-mapping, echo=FALSE, fig.height=6.2, fig.width=7.1, results="asis", eval=TRUE}
## These function definitions must be in the same block as when they are called.
Header <- function (level, content) paste0("  \n", paste0(rep('#', level), collapse=''), " ", content, "  \n")
PrintDivision <- function (parts) cat(Header(2L, paste(
  Italicize(this_char_parts[1:parts]), collapse=': ')))
PrintCharacter <- function () {
  cat(Header(3L, paste0("[", i, "] ", paste0(Italicize(
    this_char_parts[if(char_nesting[i] < 4) char_nesting[i] else 3:char_nesting[i]]),
    collapse=': '), " {-}")))
}
PrintSoloCharacter <- function () {
  cat(Header(2L, paste0(paste(
    Italicize(this_char_parts), collapse=': ')," [", i, "] ")))
}
DuplicateOf <- function (x) {
  duplicates <- duplicated(x)
  masters <- x[!duplicates]
  vapply(masters, function (d) x == d, logical(length(x)))
}
PrintStateNotes <- function (notes) {
  PrintThisNote <- function (note) {
    afflictedTaxa <- names(note)[note]
    master <- afflictedTaxa[1]
    cat(paste0("<div class='state-note' id='", master, "-coding-", i, "'>",
               paste(taxa_italic[taxa_names %in% afflictedTaxa], collapse=', '),
                      ": ", Italicize(notes[master]), "</div>  \n  \n"))
  }
  
  if (length(notes) > 0) {
    cat('  \n<div class="state-notes">')
  }
  if (length(notes) == 1) {
    onlyOne <- TRUE
    names(onlyOne) <- names(notes)
    PrintThisNote(onlyOne)
  } else {
    notes <- notes[order(names(notes))]
    duplicates <- DuplicateOf(toupper(notes))
    apply(duplicates, 2, PrintThisNote)
  }
  if (length(notes) > 0) {
    cat('</div>  \n  \n')
  }
}

prev_char_parts <- "NONE"
prev_nesting <- 0

subheadings <- c("Digestive tract: Anus: Presence",
                 "Gametes: Spermatozoa: Nucleus: Shape",
                 "Gametes: Egg: Size",
                 paste("Sclerites:",
                       c("Bivalved", "Dorsal valve: Growth direction",
                         "Ventral valve: Growth direction",
                         "Ornament: Concentric ornament",
                         "Composition: Mineralogy",
                         "Structure: Stratiform lamellae expressed at surface")),
                 paste("Larva:", c("Cilia: Metatroch", 
                    "Apical organ: Muscles extending to the hyposphere")))

#for (i in 14:17) {
for (i in seq_len(n_char)) {

  this_char_parts <- char_parts[[i]]
  next_char_parts <- if (i == n_char) "LAST_CHARACTER" else char_parts[[i + 1L]]
  this_nesting <- char_nesting[i]
  next_nesting    <- if (i == n_char) 0 else char_nesting[i + 1L]

  if ( # Reasons to print a heading
    (char_names[i] %in% subheadings ||
      this_char_parts[1] != prev_char_parts[1]) #||
    #( this_nesting > 1L && prev_nesting > 2L &&
    #  this_char_parts[2] != prev_char_parts[2]) ||
    #( this_nesting > 1L && prev_nesting > 1L && next_nesting > 2L &&
    #  this_char_parts[2] == next_char_parts[2] &&
    #  this_char_parts[2] != prev_char_parts[2])
  ) {
    if ( # Reasons to print a Solo character
      (this_char_parts[1] != next_char_parts[1] &&
       this_char_parts[1] != prev_char_parts[1]) ||
      (this_nesting == 2L && next_nesting > 1L &&
       prev_char_parts[1] == this_char_parts[1] &&
       next_char_parts[1] == this_char_parts[1]) ||
      (this_nesting == 1L && next_nesting > 1L &&
            next_char_parts[1] == this_char_parts[1]) #||
      #prev_nesting > 2L && (
        #next_nesting < 2L
        #|| (this_nesting > 1L && next_nesting > 2L &&
            #(this_char_parts[2] != next_char_parts[2]))
      #)
     ) {
     PrintSoloCharacter()
   }
   else if ( # Reasons to print a top-level heading
     this_nesting == 1 ||
     (next_nesting > 1 && (this_char_parts[2] != next_char_parts[2]))
   ) {
     PrintDivision(1)
     PrintCharacter()
   } else {
     PrintDivision(2)
     PrintCharacter()
   }
 } else { # Just print the character
   PrintCharacter()
  }
  prev_char_parts <- this_char_parts
  prev_nesting <- char_nesting[i]
  
  par(mar=rep(0.2, 4), cex=0.7)
  
  stateLabels <- my_states[[i]]
  my_chars_i <- my_chars[, i]
  
  if (my_chars_i[1] == '?' && length(unique(my_chars_i)) == 1) {
    cat("<p>All taxa are coded as ambiguous for this character.</p>")
    legendLabels <- "?: Not scored"
    legendCol <- "darkgrey"
  } else if (exists('localInstance') || knitr::is_html_output()) {
    for (treeNo in eachTree) {
      tree <- rootedTrees[[treeNo]]
      nodeXi <- nodeX[[treeNo]]
      nodeYi <- nodeY[[treeNo]]
      states_matrix <- apply.reconstruction(tree, my_chars_i)
      fitch_states <- apply.reconstruction(tree, my_chars_i, method='Fitch', inapplicable=1)
      matrix_data <- MatrixData(states_matrix, fitch_states, state.labels=stateLabels)
      legendLabels <- matrix_data$legend
      legendCol <- matrix_data$legend_col
      edgeCol <- matrix_data$edge_col
      flagCol <- matrix_data$tips_colours
      tipFlag <- matrix_data$tips_labels
      nodeSupport <- round(SplitSupport(tree, allSplits, tipIndex) / length(allTrees), 2)
      
      LineStyle <- function (x) ifelse(x == 'lightgrey', '" class="inapplicable', '')
      edges <- paste0(vapply(unique(edgeCol), function(colour) {
        theseEdges <- edgeCol == colour
        paste0('<path d="', paste0(
               'M', nodeXi[parent[treeNo, theseEdges]],
               ',', nodeYi[parent[treeNo, theseEdges]],
               'V', nodeYi[child[treeNo, theseEdges]],
               'H', nodeXi[child[treeNo, theseEdges]],
               collapse=''),
               '" stroke="', colour, LineStyle(colour), '"></path>')
      }, character(1)), collapse='')
      tips <- paste0('<text x="', (nodeXi[terminal] + 0L), 
                     '" y="', nodeYi[terminal] + textY,
                     '" fill="', flagCol[terminal],
                     '" class="flag">[', tipFlag[terminal], ']</text>',
                     '<text x="', (nodeXi[terminal] + 22L),
                     '" y="', nodeYi[terminal] + textY,
                     '" fill="', ifelse(flagCol == 'lightgrey', '#ccc', 
                                        ifelse(flagCol == 'grey', '#999', '#000')),
                     '" class="taxonLabel">', 
                     gsub('_', ' ', tipLabel[treeNo, terminal], fixed=TRUE), '</text>',
                     collapse='')
      nodes <- paste0('<text x="', (nodeXi[internal][-1] + 2L), 
                      '" y="', nodeYi[internal][-1] + textY,
                      '" class="node" fill="', NodeColour(nodeSupport[-1]),
                      '">', nodeSupport[-1], '</text>', collapse='')
      nRegions <- length(states_matrix$regions)
      if (states_matrix$score == fitch_states$score) {
        fitchNote1 <- fitchNote2 <- ''
      } else {
        fitchNote1 <- paste0(' (<tspan class="score fitch">', fitch_states$score,
                             '</tspan> with Fitch)')
        fitchNote2 <- ' (not counted by Fitch)'
      }
      ciCaption <- paste0('<text x="', svgWidth - 4L,
                   '" y="', yStep + textY, '" text-anchor="end" class="stepsLabel">',
                    'Character adds <tspan class="score">', states_matrix$score,
                   '</tspan> to tree score', fitchNote1, '</text><text x="',
                   svgWidth - 4L, '" y="', (yStep * 2) + textY, 
                   '" text-anchor="end" class="stepsLabel">',
                   '<tspan class="score">', nRegions,
                   '</tspan> additional region', ifelse(nRegions == 1, '', 's'), 
                   fitchNote2, '</text><text x="', svgWidth - 4L,
                   '" y="', (yStep * 3) + textY, '" text-anchor="end" class="stepsLabel">',
                    ci_text[i, treeNo],
                   '</text><text x="', svgWidth - 4L,
                    '" y="', (yStep * 5) + textY, '" text-anchor="end" class="stepsLabel">',
                    '<tspan dy="16" fill="#34caaf">An optimal tree under:</tspan>', 
                   paste0('<tspan x="', svgWidth - 2L,
                          '" style="font-style:italic" class="',
                          ifelse(analysisNames %in% treeNames[treeIndex==treeNo],
                                 'this', 'notThis'),
                          'An" dy="1.2em">', analysisNames, '</tspan>', collapse=''),
                    '</text>')
      dudSteps <- matrix_data$dud_steps
      naughtyNodes <- if (length(dudSteps) > 0) {
        paste0('<circle cx="', nodeXi[dudSteps], '" cy="', nodeYi[dudSteps],
               '"/><text x="', nodeXi[dudSteps] - textY, '" y="', nodeYi[dudSteps] + textY,
               '" class="dud-step">Nonsensical Fitch step</text>', collapse='')
      } else { '' }
                  
      svgSource <- paste0('<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="', 
                    svgWidth, '" height="', svgHeight, '" class="tree" data-char="', i, '">',
                    ciCaption, tips, edges, nodes, naughtyNodes,
                    '</svg>')
      write(svgSource, file=paste0('_book/', sprintf(fileNamer, treeNo, i)))
    }
    cat(svgSource)
  } else {
    plot.states.matrix(apply.reconstruction(trees[[1]], my_chars_i),
                       passes=0, counts=1:2, show.labels=1,
                       col.states=TRUE, state.labels=stateLabels,
                       use.edge.length=TRUE, legend.pos='topright')
    legend('bottomleft',  bty='n', ci_text[i, 1])
  
  }
  cat(paste0("  \n\n > **Character ", i, ": ", Italicize(char_names[i]), "**  \n>\n"))
  if (exists('localInstance') || knitr::is_html_output()) {
    lineHeight <- 24L
    legendY <- round(lineHeight * seq_along(legendLabels), 1)
    cat(paste0('>  <svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="', svgWidth, 
        '" height="', lineHeight * length(legendLabels) + lineHeight - 5L, # For T/N statement
        '" class="statesLegend">',
        paste0('<path d="M0,', legendY - 15L, 'h22" stroke="', legendCol,
                       LineStyle(legendCol), '"></path>', collapse=''),
        '<text x="30" y="-10" class="legendLabels">', 
        paste0('<tspan x="30" dy="', lineHeight, '">', legendLabels, '</tspan>', collapse=''),
        '<tspan x=0 dy="', lineHeight, '">', 
        ifelse (IsTransformational(my_states[[i]]), "Transformational", "Neomorphic"),
        ' character.</tspan>',
        '</text></svg> \n>\n'))
  } else {
    PrintStates(Italicize(my_states[[i]]))
  }
  cat("  \n\n")
  char_notes_i <- char_notes[[i]]
  state_notes_i <- char_notes_i[[2]]
  state_notes_i <- state_notes_i[!names(state_notes_i) %in% ignored_taxa]
  if (length(char_notes_i[[1]]) > 0) cat(Italicize(char_notes_i[[1]]), "  \n")
  if (length(state_notes_i) > 0) PrintStateNotes(state_notes_i)
  if (my_states[[i]][[1]] != "''") PrintNaughtyInapplicables(my_chars[, i])
  cat("  \n") # Clear line, ready for next block
}
if (exists('localInstance') || knitr::is_html_output()) {
  cat(paste0('<div class="switcher">',
    '<span class="selectTree">Tree number:</span>',
    '<input class="switcherNumber" type="number" min="1" max="',
    n_tree, '"  oninput="switchTree(this)" value="', n_tree, '"></input>',
    '</div>'))
}
```
