---
title: "Taxonomic implications"
author: "Martin R. Smith"
---

# Taxonomic implications

This section briefly places key features of our results in the context of previous phylogenetic hypotheses.  For brevity, we refer to the method of @Brazeau2018 as "inapplicable-corrected" parsimony, as it corrects for errors arising from the handling of inapplicable data in standard Fitch parsimony.

Crown- and stem-group terminology has great value in clarifying the early evolution of major lineages [@Budd2000;@Carlson2009].  The crown group of a lineage is defined as the last common ancestor of all living members of a group, and all its descendants; the stem group as all taxa more closely related to the crown group than to any other extant taxon.  In our selection of taxa, the brachiopod crown group corresponds to the last common ancestor of _Terebratulina_, _Novocrania_, _Pelagodiscus_ and _Lingula_; the brachiopod stem group comprises anything between this node and the branching point of _Phoronis_, which marks the base of the Brachiozoan crown group.

Hyoliths
: Hyoliths as a whole are interpreted as stem-group Brachiopods, which refines the broader phylogenetic position proposed by @Moysiuk2017Hyolithsare.  This is to say, they sit closer to brachiopods than the phoronids do, but no analysis places them within the Brachiopod crown group.
: Tommotiids lie both stemwards (e.g. _Eccentrotheca_) and crownwards (_Mickwitzia_) of hyoliths, which thus represent derived tommotiids.  
: Within the hyoliths, orthothecids are consistently recovered as a grade that is paraphyletic to the hyolithids.  

Tommotiids
: Tommotiids represent a basal grade, paraphyletic to phoronids and crown-group brachiopods, in line with previous interpretations.  
: _Mickwitzia_ is consistently the most crownwards of the tommotiids, falling as sister to the brachiopod crown group (except in the Bayesian results, where they fall within the paraphyletic craniiform grade).   _Mickwitzia_ is closely related to _Micrina_ and _Heliomedusa_, though the exact nature of this relationship varies from analysis to analysis. The latter affilitation reflects similarities emphasized by Holmer and Popov in @Williams2007Supplement. <!--, but plots instead within the Craniiforms under certain analytical conditions, in line with earlier interpretations [@Williams2000LinguliformeaCraniiformea].-->
: _Dailyatia_ tends to plot closely with _Halkieria_, reflecting the similarity in the form of their proposed scleritome [@Skovsted2015Theearly].  Bayesian analysis recovers this pair as sister to annelids and molluscs; Fitch parsimony places them in the molluscan stem group.  Inapplicable-corrected parsimony instead places these taxa as sister to hyoliths + brachiopods [cf. @Zhao2017].

Craniiforms
: Trimerellids are reconstructed as paraphyletic with respect to Craniiforms.  This is consistent with the affinity commonly drawn between these groups [e.g. @Williams2000LinguliformeaCraniiformea], and helps to account for the stratigraphically late (Ordovician) appearance of Craniids in the fossil record.  (Aragonite is underrepresented in early Palaeozoic strata due to taphonomic bias.)  
: The position of the craniiforms is not conclusively resolved; shell characters point to a relationship with the Rhynchonelliforms, which is countered by similarities between the spermatozoa of phoronids and terebratulids, indicating a craniiform + linguliform clade.  This latter relationship is preferred by Fitch and inapplicable-corrected parsimony analyses.
: The Bayesian results offer a more surprising interpretation that places the craniiforms as paraphyletic with respect to all other brachiopods, with _Gasconsia_ representing the basalmost member of the Rhynchonellid lineage, upholding suggestions [@Holmer2014OrdovicianSilurian] of a chileid rather than trimerellid affinity.  To our knowledge, the hypothesis of a paraphyletic craniiform + trimerellid grade has never been proposed, and represents a poor fit to stratigraphic data; potentially it represents an artefact resulting from the incorrect handling of inapplicable data within the Mk model.

Rhynchonelliforms
: The position of kutorginids within the rhynchonelliform stem lineage has been tricky to resolve [@Holmer2018Theattachment]. Inapplicable-corrected parsimony places them sister to Rhynchonelliforms; Fitch parsimony places them as sister to the Chileids; and Bayesian analysis conservatively fails to distinguish between these two possibilities. These results are broadly in accord with previous proposals [@Holmer2018Evolutionarysignificance]. The protorthid _Glyptoria_ is the earliest diverging of the included rhynchonelliform lineages. 

: _Salanygolina_ has been interpreted as a stem-group rhynchonelliform based on its combination of paterinid and chileate features [@Holmer2009Theenigmatic].  Our results position _Salanygolina_ as sister either to the Chileids or the Chileids + Rhynchonelliforms, corroborating this interpretation.

: Basal rhynchonellids are characterized by a circular umbonal perforation in the ventral valve, associated with a colleplax.  Partly on this basis, the aberrant taxa _Yuganotheca_ and _Tomteluva_ tend to plot close to the chileids under Fitch and Bayesian analysis, though a variety of positions in this region of the tree are equally plausible.  Inapplicable-corrected parsimony, in contrast, supports the interpretation of _Yuganotheca_ as a stem-group brachiopod  [@Zhang2014Anearly].

Paterinids
: Paterinids have traditionally been placed within the Linguliforms on the basis of their phosphatic shell [@Williams2007Supplement], which we identify as ancestral within the brachiopod crown group; consequently, our analysis places the paterinids within the Rhynchonelliforms instead.  Characters supporting this position include the strophic hinge line, planar cardinal area, the absence of a pedicle nerve impression, and the morphology of the mantle canals.
: More generally, although some lingulids can be found which share more generic characters (e.g. shell growth direction) with paterinids, the particular combination of characters exhibited in paterinids does not occur anywhere in the linguliform lineage, but is more similar to that of basal rhynchonelliforms, particularly _Salanygolina_ [as noted by @Holmer2009Theenigmatic].

Linguliforms
: The reconstruction of Linguloformea comprising Linguloidea as sister to Discinoidea is as expected.  Lingulellotretids also sit within this linguliform grouping; a position in the phoronid stem lineage [advocated by @Balthasar2009EarlyCambrian] is not upheld.  Acrotretids and Siphonotretids form a clade with _Lingulosacculus_.
: More novel is the reconstruction of the calcitic obolellid _Mummpikia_ in the linguliform total group: a rhynchonelliform affinity has been assumed based on its calcitic mineralogy. This said, @Balthasar2008iMummpikia has highlighted the similarities between obolellids and linguliform brachiopods, including sub-&mu;m vertical canals and the detailed configuration of the posterior shell margin.
Our analyses uphold the case for a linguliform affinity for _Mummpikia_; a calcitic shell seemingly arose through an independent change within this taxon  As such, _Mummpikia_ has no direct bearing on the origin of 'Calciata', save that shell mineralogy is perhaps less static than commonly assumed.
: More generally, our results identify Class Obolellata as polyphyletic:  _Alisina_ (Trematobolidae) plots within Rhynchonellata;  _Tomteluva_ is harder to place, but tends to group with _Salanygolina_ stemwards of the chileids.

Outgroup
: All analyses recover the same phylum-level relationships between the outgroup taxa.  Whereas the rooting of Lophotrochozoa is beyond the scope of this analysis, annelids and molluscs are recovered as more closely related to each other than to any other group, with Entoprocta (Kamptozoa) representing their closest relative.  Ectoprocta (Bryozoa) are recovered as the closest relatives of Brachiozoa (=Phoroinda + Brachiopoda).
: As the analysis was not constructed to test the relationships of outgroup taxa, some caution is due in interpreting these results; outgroup taxa include single representatives of diverse and ancient phyla, and are thus prone to long branch error [@Parks2014].  The relationships of the lophotrochozoan phyla were not the primary object of this study, and have long resisted elucidation; this said, we have attempted to incorporate all morphological evidence that has been interpreted as informing relationships between these groups.  
: In this context, it is perhaps unsurprising that the narrow selection of fossil representatives of outgroup taxa, included to break long branches at the base of each clade, plot somewhat differently in different analyses.  _Wiwaxia_ consistently plots with a molluscan affiliation, but Bayesian and inapplicable-corrected parsimony analyses place it as a stem-group mollusc, whereas Fitch parsimony includes it in the molluscan crown.  _Halkieria_, _Cotyledion_, _Eccentrotheca_ and _Dailyatia_ are recovered as close relatives, forming a grade in the brachiopod stem group under inapplicable-corrected parsimony, a clade in the molluscan stem group in Fitch parsimony, and a polytomy at a deeper node under Bayesian analysis.  
_Namacalathus_ is reconstructed as a basal Brachiozoan under inapplicable-corrected parsimony and Bayesian analysis, and a stem-group brachiopod under Fitch parsimony.
