\documentclass[openany]{book}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Supplementary Information for: Hyoliths with pedicles constrain the origin of the brachiopod body plan},
            pdfauthor={Haijing Sun, Martin R. Smith, Han Zeng, Fangchen Zhao, Guoxiang Li and Maoyan Zhu},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{natbib}
\bibliographystyle{apalike-doi}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\usepackage{longtable,booktabs}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Supplementary Information for: \newline\newline Hyoliths with pedicles
constrain the origin of the brachiopod body plan}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Haijing Sun, Martin R. Smith, Han Zeng, Fangchen Zhao, Guoxiang Li and
Maoyan Zhu}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{2018-06-19}

\usepackage{doi} % Adds hyperlinks to dois
\setcitestyle{round}
\usepackage{hyperref}
\usepackage[nottoc]{tocbibind} % list references in TOC
\raggedbottom % already in pnas-new
\usepackage[section]{placeins}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\chapter*{Supplementary Text}\label{supplementary-text}
\addcontentsline{toc}{chapter}{Supplementary Text}

This document comtains supplementary material to
\citet{Sun2018Hyolithswith}. It is best viewed in HTML format at
\href{https://ms609.github.io/hyoliths/}{ms609.github.io/hyoliths}.

It describes the \protect\hyperlink{dataset}{morphological dataset} and
the results of tree searches using \protect\hyperlink{fitch}{Fitch
parsimony} and a \protect\hyperlink{bayesian}{Bayesian method}:
approaches that are subject to errors resulting from logically
incoherent treatment of inapplicable data \citep{Maddison1993}. We also
present the \protect\hyperlink{treesearch}{results} of tree searches
with the algorithm described by \citet{Brazeau2018}, which correctly
handles inapplicable data in a parsimony setting. Finally, we document
how each character is most parsimoniously
\protect\hyperlink{reconstructions}{reconstructed} on an optimal tree.

Supplementary \protect\hyperlink{figures}{figures} and
\protect\hyperlink{table}{tables} appear after the text.

\hypertarget{dataset}{\chapter{Phylogenetic dataset}\label{dataset}}

Analysis was performed on a new matrix of 54 lophotrochozoan taxa, coded
for 225 morphological characters (129 neomorphic, 96 transformational).
The matrix can be viewed interactively at Morphobank
(\href{https://morphobank.org/permalink/?P2800}{project 2800}) {[}This
dataset will be released on publication of the paper. Referee access is
availble by
\href{https://morphobank.org/index.php/LoginReg/form}{logging in to
MorphoBank} using the e-mail address and password given in the
manuscript.{]}; a static version can be downloaded directly :

\begin{itemize}
\item
  \href{https://raw.githubusercontent.com/ms609/hyoliths/master/mbank_X24932_6-15-2018_519.nex}{raw.githubusercontent.com/ms609/hyoliths/master/mbank\_X24932\_6-15-2018\_519.nex}
  (Nexus format)
\item
  \href{https://raw.githubusercontent.com/ms609/hyoliths/master/mbank_X24932_6-15-2018_519.tnt}{raw.githubusercontent.com/ms609/hyoliths/master/mbank\_X24932\_6-15-2018\_519.tnt}
  (TNT format).
\end{itemize}

Taxa include sipunculans and molluscs, which have previously been
interpreted as having affinities with hyoliths. Other lophotrochozoan
groups help to constrain the outgroup topology, and a diversity of
brachiozoans helps to resolve the position of hyoliths within this
group.

Characters are coded following the recommendations of
\citet{Brazeau2018}:

\begin{itemize}
\item
  We have employed reductive coding, using a distinct state to mark
  character inapplicability. Character specifications follow the
  structural syntax of \citet{Sereno2007} in order to highlight
  ontological dependence between characters and emphasize the structure
  of the dataset.
\item
  We have distinguished between neomorphic and transformational
  characters \citep[sensu][]{Sereno2007} by reserving the token
  \texttt{0} to refer to the absence of a neomorphic
  (i.e.~presence/absence) character. The states of transformational
  characters (i.e.~characters that describe a property of a feature) are
  represented by the tokens \texttt{1}, \texttt{2}, \texttt{3}, \ldots{}
\item
  We code the absence of neomorphic ontologically dependent characters
  \citep[sensu][]{Vogt2017} as absence, rather than inapplicability.
\end{itemize}

The complete dataset comprises 12150 character codings, of which 1133
are inapplicable and 4975 were positive statements (i.e.~neither
ambiguous nor inapplicable). This latter value, the amount and quality
of data that \emph{is} coded, is more instructive than the number of
cells that are ambiguous \citep{Wiens1998, Wiens2003}. Of the 225
characters, the number that were coded with an applicable token for each
taxon is:

\begin{tabular}{l|l|l|l|l|l}
\hline
 &  &  &  &  & \\
\hline
\_Acanthotretella spinosa\_ & 70 & \_Gasconsia\_ & 70 & \_Novocrania\_ & 186\\
\hline
\_Alisina\_ & 84 & \_Glyptoria\_ & 73 & \_Orthis\_ & 70\\
\hline
\_Amathia\_ & 157 & \_Halkieria evangelista\_ & 65 & \_Paramicrocornus\_ & 57\\
\hline
\_Antigonambonites planus\_ & 85 & \_Haplophrentis carinatus\_ & 82 & \_Paterimitra\_ & 67\\
\hline
\_Askepasma toddense\_ & 78 & \_Heliomedusa orienta\_ & 67 & \_Pauxillites\_ & 56\\
\hline
\_Bactrotheca\_ & 53 & \_Kutorgina chengjiangensis\_ & 84 & \_Pedunculotheca diania\_ & 63\\
\hline
\_Botsfordia\_ & 75 & \_Lingula\_ & 205 & \_Pelagodiscus atlanticus\_ & 166\\
\hline
\_Clupeafumosus socialis\_ & 76 & \_Lingulellotreta malongensis\_ & 87 & \_Phoronis\_ & 169\\
\hline
\_Conotheca\_ & 60 & \_Lingulosacculus\_ & 60 & \_Salanygolina\_ & 79\\
\hline
\_Coolinia pecten\_ & 80 & \_Longtancunella chengjiangensis\_ & 61 & \_Serpula\_ & 170\\
\hline
\_Cotyledion tylodes\_ & 65 & \_Loxosomella\_ & 164 & \_Siphonobolus priscus\_ & 74\\
\hline
\_Craniops\_ & 66 & \_Maxilites\_ & 61 & \_Sipunculus\_ & 168\\
\hline
\_Cupitheca holocyclata\_ & 63 & \_Mickwitzia muralensis\_ & 72 & \_Terebratulina\_ & 184\\
\hline
\_Dailyatia\_ & 55 & \_Micrina\_ & 71 & \_Tomteluva perturbata\_ & 58\\
\hline
\_Dentalium\_ & 169 & \_Micromitra\_ & 81 & \_Tonicella\_ & 188\\
\hline
\_Eccentrotheca\_ & 54 & \_Mummpikia nuda\_ & 55 & \_Ussunia\_ & 53\\
\hline
\_Eoobolus\_ & 81 & \_Namacalathus\_ & 59 & \_Wiwaxia corrugata\_ & 75\\
\hline
\_Flustra\_ & 168 & \_Nisusia sulcata\_ & 80 & \_Yuganotheca elegans\_ & 56\\
\hline
\end{tabular}

\hypertarget{fitch}{\chapter{Fitch parsimony}\label{fitch}}

Parsimony search with the \citet{Fitch1971} algorithm was conducted in
TNT v1.5 \citep{Goloboff2016} using Ratchet and tree drifting heuristics
\citep{Goloboff1999, Nixon1999}, repeating the search until the optimal
score had been hit by 1500 independent searches:

\begin{quote}
xmult:rat10 drift10 hits 1500 level 4 chklevel 5;
\end{quote}

Searches were conducted under equal weights and results saved to file:

\begin{quote}
piwe-; xmult; {/* Conduct search with equal weighting */}

tsav *TNT/ew.tre;sav;tsav/; {/* Save results to file */}
\end{quote}

Node support was estimated by calculating the proportion of jackknife
replicates in which each group occurred, using 5000 symmetric resampling
iterations, following the recommendations of \citet{Kopuchian2010} and
\citet{Simmons2011}.

\begin{quote}
var: nt; {/* Define a variable to track tree address */}

nelsen *; {/* Generate strict consensus tree */}

set nt ntrees; ttag=; {/* Prepare for resampling */}

resample=sym 5000 frequency from `nt'; {/* Symmetric resampling,
counting frequencies */}

log TNT/ew.sym; ttag/; log/; {/* Write results to log */}

keep 0; ttag-; hold 10000; {/* Clear memory */}
\end{quote}

Further searches were conducted under extended implied weighting
\citep{Goloboff1997, Goloboff2014}, under the concavity constants 2, 3,
4.5, 7, 10.5, 16 and 24:

\begin{quote}
xpiwe=; {/* Enable extended implied weighting */}

piwe=2; xmult; {/* Conduct analysis at k = 2 */}

tsav *TNT/xpiwe2.tre; sav; tsav/; {/* Save results to file */}

nelsen *; set nt ntrees; ttag=; {/* Prepare for resampling */}

resample=frequency from `nt'; {/* Symmetric resampling */}

log TNT/ew.sym; ttag/; log/; {/* Write results to log */}

keep 0; ttag-; hold 10000; {/* Clear memory */}

{/* Repeat this block for each value of k */}
\end{quote}

Results can be replciated by:

\begin{itemize}
\item
  \begin{description}
  \tightlist
  \item[Downloading
  \href{https://raw.githubusercontent.com/ms609/hyoliths/master/mbank_X24932_6-15-2018_519.tnt}{the
  data in TNT format}]
  \href{https://raw.githubusercontent.com/ms609/hyoliths/master/mbank_X24932_6-15-2018_519.tnt}{raw.githubusercontent.com/ms609/hyoliths/master/mbank\_X24932\_6-15-2018\_519.tnt}
  \end{description}
\item
  Save
  \href{https://raw.githubusercontent.com/ms609/hyoliths/master/tnt.run}{the
  script above} to the same directory, with the filename
  \texttt{tnt.run}.
\item
  Open TNT, type \texttt{piwe=} before you load the downloaded dataset
  (to enable extended implied weighting), then type \texttt{tnt} into
  the command box to run the script.
\item
  We acknowledge the Willi Hennig Society for their sponsorship of the
  TNT software.
\end{itemize}

\section{Results}\label{results}

\includegraphics{Brachiopod_phylogeny_files/figure-latex/tnt-iw-overview-1.pdf}









\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/tnt-iw-consensus-1.pdf}
\caption{\label{fig:tnt-iw-consensus}Strict consensus of all trees recovered by TNT
using Fitch parsimony with implied weighting at all values of \emph{k}, and at the individual
values \emph{k} = 2, 3 and 4.5.
The consensus of all implied weights runs is
not very well resolved, largely due to a few wildcard taxa, particularly
at \(k = 4.5\), which obscures a consistent set of relationships between
the remaining taxa.}
\end{figure}

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/tnt-iw-7-24-1.pdf}
\caption{\label{fig:tnt-iw-7-24}Strict consensus of all trees recovered by TNT
using Fitch parsimony with implied weighting, at \emph{k} = 7, 10.5, 16 and 24.}
\end{figure}

\newpage




\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/tnt-ew-consensus-1.pdf}
\caption{\label{fig:tnt-ew-consensus}Consensus of all trees obtained using equally weighted
Fitch parsimony in TNT. Nodes labelled with jackknife frequencies.}
\end{figure}

\hypertarget{bayesian}{\chapter{Bayesian analysis}\label{bayesian}}

Bayesian search was conducted in MrBayes v3.2.6 \citep{Ronquist2012}
using the Mk model \citep{Lewis2001} with gamma-distributed rate
variation across characters:

\begin{quote}
lset coding=variable rates=gamma;
\end{quote}

Branch length was drawn from a dirichlet prior distribution, which is
less informative than an exponential model \citep{Rannala2012}, but
requires a prior mean tree length within about two orders of magnitude
of the true value \citep{Zhang2012}. To satisfy this latter criterion,
we specified the prior mean tree length to be equal to the length of the
most parsimonious tree under equal weights, using a Dirichlet prior with
\(\alpha_T = 1\), \(\beta_T = 1/(\)\emph{equal weights tree
length}\(/\)\emph{number of characters}\()\), \(\alpha = c = 1\):

\begin{quote}
prset brlenspr = unconstrained: gammadir(1, 0.35, 1, 1);
\end{quote}

Neomorphic and transformational characters
\citep[\emph{sensu}][]{Sereno2007} were allocated to two separate
partitions whose proportion of invariant characters and gamma shape
parameters were allowed to vary independently:

\begin{quote}
charset Neomorphic = 1 6 7 9 10 15 18 19 20 21 22 24 26 29 30 34 35 37
38 40 43 44 45 48 49 53 54 55 56 57 58 59 60 61 65 66 68 69 71 76 78 79
80 81 83 86 87 88 91 92 93 94 97 98 99 100 101 102 106 108 109 111 118
119 121 122 125 126 129 136 137 138 139 140 142 143 144 145 148 150 151
153 154 155 156 157 158 160 164 168 170 174 175 176 177 179 180 181 182
183 184 185 186 187 188 190 192 193 196 199 202 203 204 205 206 207 209
210 211 212 214 215 216 217 218 219 220 222 225;

charset Transformational = 2 3 4 5 8 11 12 13 14 16 17 23 25 27 28 31 32
33 36 39 41 42 46 47 50 51 52 62 63 64 67 70 72 73 74 75 77 82 84 85 89
90 95 96 103 104 105 107 110 112 113 114 115 116 117 120 123 124 127 128
130 131 132 133 134 135 141 146 147 149 152 159 161 162 163 165 166 167
169 171 172 173 178 189 191 194 195 197 198 200 201 208 213 221 223 224;

partition chartype = 2: Neomorphic, Transformational;

set partition = chartype;

unlink shape=(all) pinvar=(all);
\end{quote}

Neomorphic characters were not assumed to have a symmetrical transition
rate -- that is, the probability of the absent → present transition was
allowed to differ from that of the present → absent transition, being
drawn from a uniform prior:

\begin{quote}
prset applyto=(1) symdirihyperpr=fixed(1.0);
\end{quote}

The rate of variation in neomorphic characters was also allowed to vary
from that of transformational characters:

\begin{quote}
prset applyto=(1) ratepr=variable;
\end{quote}

\emph{Loxosomella} was selected as an outgroup:

\begin{quote}
outgroup Loxosomella;
\end{quote}

Four MrBayes runs were executed, each sampling eight chains for
5~000~000 generations, with samples taken every 500 generations. The
first 10\% of samples were discarded as burn-in.

\begin{quote}
mcmcp ngen=5000000 samplefreq=500 nruns=4 nchains=8 burninfrac=0.1;
\end{quote}

A posterior tree topology was derived from the combined posterior sample
of all runs. Convergence was indicated by PSRF = 1.00 and an estimated
sample size of \textgreater{} 200 for each parameter. Nodes are labelled
with posterior probabilities; recall that caution must be applied when
interpreting these values \citep{Yang2018}.

The Nexus file used to generate these results in MrBayes can be
\href{https://raw.githubusercontent.com/ms609/hyoliths/master/MrBayes/hyo.nex}{raw.githubusercontent.com/ms609/hyoliths/master/MrBayes/hyo.nex},
and run in \href{http://mrbayes.sourceforge.net/download.php}{MrBayes}
by typing \texttt{exe\ path/to/download}.

\section{Parameter estimates}\label{parameter-estimates}

\begin{tabular}{l|r|r|r|r|r}
\hline
Parameter & Mean & Variance & minESS & avgESS & PSRF\\
\hline
TL\{all\} & 9.980 & 0.50100 & 5440 & 5970 & 0.99999\\
\hline
m\{1\} & 0.462 & 0.00265 & 3100 & 3720 & 0.99999\\
\hline
\end{tabular}

\section{Results}\label{results-1}

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/mrbayes-full-consensus-1.pdf}
\caption{\label{fig:mrbayes-full-consensus}Results of Bayesian analysis,
posterior probability \textgreater{} 50\%, all taxa}
\end{figure}

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/mrbayes-pruned-consensus-1.pdf}
\caption{\label{fig:mrbayes-pruned-consensus}Results of Bayesian analysis,
posterior probability \textgreater{} 50\%, wildcard taxa pruned}
\end{figure}

\hypertarget{treesearch}{\chapter{Corrected
parsimony}\label{treesearch}}

The phylogenetic dataset contains a considerable proportion of
inapplicable codings (1133/12150 = 9.3\% of tokens), which are known to
introduce error and bias to phylogenetic reconstruction when the Fitch
algorithm is employed \citep{Maddison1993, Brazeau2018}. As such, we
employed a new tree-scoring algorithm that correctly handles
inapplicable data \citep{Brazeau2018}, implemented in the
\emph{MorphyLib} C library \citep{Brazeau2017Morphylib}. We employed the
R package \emph{TreeSearch} v0.1.2 \citep{Smith2018TreeSearch} to
conduct phylogenetic tree search with this algorithm.

\section{Search parameters}\label{search-parameters}

Heuristic searches were conducted using the parsimony ratchet
\citep{Nixon1999} under equal and implied weights \citep{Goloboff1997}.
The consensus tree presented in the main manuscript represents a strict
consensus of all trees that are most parsimonious under one or more of
the concavity constants (\emph{k}) 2, 3, 4.5, 7, 10.5, 16 and 24, an
approach that has been shown to produce higher accuracy (i.e.~more nodes
and quartets resolved correctly) than equal weights at any given level
of precision \citep{Smith2017}.

\section{Analysis}\label{analysis}

The R commands used to conduct the analysis are reproduced below. The
results can most readily be replicated using the
\href{https://github.com/ms609/hyoliths/}{R markdown files} (.Rmd) used
to generate these pages: in Rstudio, run
\href{https://raw.githubusercontent.com/ms609/hyoliths/master/index.Rmd}{raw.githubusercontent.com/ms609/hyoliths/master/index.Rmd},
then run each block in
\href{https://raw.githubusercontent.com/ms609/hyoliths/master/14_TreeSearch.Rmd}{raw.githubusercontent.com/ms609/hyoliths/master/14\_TreeSearch.Rmd}.
The complete analysis will take several hours.

\subsection{Initialize and load data}\label{initialize-and-load-data}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Load data from locally downloaded copy of MorphoBank matrix}
\NormalTok{my_data <-}\StringTok{ }\KeywordTok{ReadAsPhyDat}\NormalTok{(nexusFile)}
\NormalTok{my_data[ignored_taxa] <-}\StringTok{ }\OtherTok{NULL}
\NormalTok{iw_data <-}\StringTok{ }\KeywordTok{PrepareDataIW}\NormalTok{(my_data)}
\end{Highlighting}
\end{Shaded}

\subsection{Generate starting tree}\label{generate-starting-tree}

Start by quickly rearranging a neighbour-joining tree, rooted on the
outgroup.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{nj.tree <-}\StringTok{ }\KeywordTok{NJTree}\NormalTok{(my_data)}
\NormalTok{rooted.tree <-}\StringTok{ }\KeywordTok{EnforceOutgroup}\NormalTok{(nj.tree, outgroup)}
\NormalTok{start.tree <-}\StringTok{ }\KeywordTok{TreeSearch}\NormalTok{(}\DataTypeTok{tree=}\NormalTok{rooted.tree, }\DataTypeTok{dataset=}\NormalTok{my_data, }\DataTypeTok{maxIter=}\DecValTok{3000}\NormalTok{,}
                         \DataTypeTok{EdgeSwapper=}\NormalTok{RootedNNISwap, }\DataTypeTok{verbosity=}\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Implied weights analysis}\label{implied-weights-analysis}

The position of the root does not affect tree score, so we keep it fixed
(using \texttt{RootedXXXSwap} functions) to avoid unnecessary swaps.

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in}\NormalTok{ kValues) \{}
\NormalTok{  iw.tree <-}\StringTok{ }\KeywordTok{IWRatchet}\NormalTok{(start.tree, iw_data, }\DataTypeTok{concavity=}\NormalTok{k,}
                       \DataTypeTok{ratchHits =} \DecValTok{20}\NormalTok{, }\DataTypeTok{ratchIter=}\DecValTok{4000}\NormalTok{, }\DataTypeTok{searchHits=}\DecValTok{56}\NormalTok{,}
                       \DataTypeTok{swappers=}\KeywordTok{list}\NormalTok{(RootedTBRSwap, RootedSPRSwap, RootedNNISwap),}
                       \DataTypeTok{verbosity=}\NormalTok{0L)}
\NormalTok{  score <-}\StringTok{ }\KeywordTok{IWScore}\NormalTok{(iw.tree, iw_data, }\DataTypeTok{concavity=}\NormalTok{k)}
  \CommentTok{# Write a single best tree}
  \KeywordTok{write.nexus}\NormalTok{(iw.tree,}
              \DataTypeTok{file=}\KeywordTok{paste0}\NormalTok{(}\StringTok{"TreeSearch/hy_iw_k"}\NormalTok{, k, }\StringTok{"_"}\NormalTok{, }
                          \KeywordTok{signif}\NormalTok{(score, }\DecValTok{5}\NormalTok{), }\StringTok{".nex"}\NormalTok{, }\DataTypeTok{collapse=}\StringTok{''}\NormalTok{))}

\NormalTok{  iw.consensus <-}\StringTok{ }\KeywordTok{IWRatchetConsensus}\NormalTok{(iw.tree, iw_data, }\DataTypeTok{concavity=}\NormalTok{k,}
                  \DataTypeTok{swappers=}\KeywordTok{list}\NormalTok{(RootedTBRSwap, RootedNNISwap),}
                  \DataTypeTok{searchHits=}\DecValTok{55}\NormalTok{, }\DataTypeTok{searchIter=}\DecValTok{4000}\NormalTok{, }\DataTypeTok{nSearch=}\DecValTok{250}\NormalTok{, }\DataTypeTok{verbosity=}\NormalTok{0L)}
  \KeywordTok{write.nexus}\NormalTok{(iw.consensus, }
              \DataTypeTok{file=}\KeywordTok{paste0}\NormalTok{(}\StringTok{"TreeSearch/hy_iw_k"}\NormalTok{, k, }\StringTok{"_"}\NormalTok{, }
                          \KeywordTok{signif}\NormalTok{(}\KeywordTok{IWScore}\NormalTok{(iw.tree, iw_data, }\DataTypeTok{concavity=}\NormalTok{k), }\DecValTok{5}\NormalTok{),}
                          \StringTok{".all.nex"}\NormalTok{, }\DataTypeTok{collapse=}\StringTok{''}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\subsection{Equal weights analysis}\label{equal-weights-analysis}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ew.tree <-}\StringTok{ }\KeywordTok{Ratchet}\NormalTok{(start.tree, my_data, }\DataTypeTok{verbosity=}\NormalTok{0L,}
                   \DataTypeTok{ratchHits =} \DecValTok{20}\NormalTok{, }\DataTypeTok{ratchIter=}\DecValTok{4000}\NormalTok{, }\DataTypeTok{searchHits=}\DecValTok{55}\NormalTok{, }\CommentTok{# ratchHits = 20 not enough}
                   \DataTypeTok{swappers=}\KeywordTok{list}\NormalTok{(RootedTBRSwap, RootedSPRSwap, RootedNNISwap))}
\NormalTok{ew.consensus <-}\StringTok{ }\KeywordTok{RatchetConsensus}\NormalTok{(ew.tree, my_data, }\DataTypeTok{nSearch=}\DecValTok{250}\NormalTok{, }\DataTypeTok{searchHits =} \DecValTok{85}\NormalTok{,}
                                 \DataTypeTok{swappers=}\KeywordTok{list}\NormalTok{(RootedTBRSwap, RootedNNISwap),}
                                 \DataTypeTok{verbosity=}\NormalTok{0L)}
\KeywordTok{write.nexus}\NormalTok{(ew.consensus, }\DataTypeTok{file=}\KeywordTok{paste0}\NormalTok{(}\DataTypeTok{collapse=}\StringTok{''}\NormalTok{, }\StringTok{"TreeSearch/hy_ew_"}\NormalTok{,}
                                      \KeywordTok{Fitch}\NormalTok{(ew.tree, my_data), }\StringTok{".nex"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\section{Results}\label{results-2}







\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-maj-consensus-1.pdf}
\caption{\label{fig:treesearch-maj-consensus}Consensus of all parsimony trees, under equal and
implied weights.
Node labels denote the frequency of each clade in
most parsimonious trees under all analytical conditions.}
\end{figure}




\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-maj-consensus-pruned-1.pdf}
\caption{\label{fig:treesearch-maj-consensus-pruned}Consensus of same trees, with taxa pruned before
constructing consensus to give context to clade support.
Node labels denote the frequency of each clade in
most parsimonious trees under all analytical conditions.}
\end{figure}





\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-iw-consensus-1.pdf}
\caption{\label{fig:treesearch-iw-consensus}Strict consensus of implied weights analyses at all
values of \emph{k}. Wildcard taxa have been excluded from the consensus
tree shown above to improve resolution.}
\end{figure}








\clearpage 

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-all-iw-results-1.pdf}
\caption{\label{fig:treesearch-all-iw-results}Strict consensus trees of implied weights analyses
at all values of \emph{k}, and at the individual
values \emph{k} = 2, 3 and 4.5.}
\end{figure}

\clearpage 

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-iw-results-3-1.pdf}
\caption{\label{fig:treesearch-iw-results-3}Strict consensus trees of implied weights analyses
at \emph{k} = 7, 10.5, 16 and 24.}
\end{figure}

\clearpage

\begin{figure}
\centering
\includegraphics{Brachiopod_phylogeny_files/figure-latex/treesearch-equal-weights-results-1.pdf}
\caption{\label{fig:treesearch-equal-weights-results}Strict consensus of
most parsimonious trees under equally weighted parsimony}
\end{figure}

\clearpage

\hypertarget{reconstructions}{\chapter{Character
reconstructions}\label{reconstructions}}

This page provides definitions for each of the characters in our matrix,
and justifies codings in particular taxa where relevant. Further
citations for codings that are not discussed in the text can be viewed
by browsing the \protect\hyperlink{dataset}{morphological dataset} on
MorphoBank (\href{https://morphobank.org/permalink/?P2800}{project
2800}). {[}This dataset will be released on publication of the paper.
Referee access is availble by
\href{https://morphobank.org/index.php/LoginReg/form}{logging in to
MorphoBank} using the e-mail address and password given in the
manuscript.{]}

Alongside its definition, each character has been mapped onto a tree.
Here, we have arbitrarily selected one most parsimonious tree obtained
under implied weighting, \(k = 4.5\). Other trees can be viewed in the
HTML version of this document at
\href{https://ms609.github.io/hyoliths/reconstructions.html}{ms609.github.io/hyoliths}.
Each tip is labelled according to its coding in the matrix. These states
have been used to reconstruct the condition of each internal node, using
the parsimony method of \citet{Brazeau2018} as implemented in the
\emph{R} package \emph{Inapp}.

We emphasize that different trees will give different reconstructions.
The character mappings are not intended to definitively establish how
each character evolved, but to help the reader quickly establish how
each character has been coded, and to visualize at a glance how each
character fits onto a given tree.







\includegraphics{Brachiopod_phylogeny_files/figure-latex/all-changes-1.pdf}

\chapter{Taxonomic implications}\label{taxonomic-implications}

This section briefly places key features of our results in the context
of previous phylogenetic hypotheses.

\begin{description}
\item[Outgroup]
We advise caution in the interpretation of outgroup relationships.
Outgroup taxa include single representatives of diverse and ancient
phyla, and are thus prone to long branch error \citep{Parks2014}. The
relationships of the lophotrochozoan phyla were not the primary object
of this study, and have long resisted elucidation; this said, we have
attempted to incorporate all morphological evidence that has been
interpreted as informing relationships between these groups.
\item[Brachiopod crown and stem group]
Crown- and stem-group terminology has great value in clarifying the
early evolution of major lineages \citep{Budd2000, Carlson2009}. The
crown group of a lineage is defined as the last common ancestor of all
living members of a group, and all its descendants; the stem group as
all taxa more closely related to the crown group than to any other
extant taxon. In our selection of taxa, the brachiopod crown group
corresponds to the last common ancestor of \emph{Terebratulina},
\emph{Novocrania}, \emph{Pelagodiscus} and \emph{Lingula}; the
brachiopod stem group comprises anything between this node and the
branching point of \emph{Phoronis}, which marks the base of the
Brachiozoan crown group.
\item[Craniiforms]
Trimerellids are reconstructed as paraphyletic with respect to
Craniiforms. This is consistent with the affinity commonly drawn between
these groups \citep[e.g.][]{Williams2000LinguliformeaCraniiformea}, and
helps to account for the stratigraphically late (Ordovician) appearance
of Craniids in the fossil record. (Aragonite is underrepresented in
early Palaeozoic strata due to taphonomic bias.)

The position of the craniiforms is not conclusively resolved; shell
characters point to a relationship with the Rhynchonelliforms, which is
countered by similarities between the spermatozoa of phoronids and
terebratulids, indicating a craniiform + linguliform clade. This latter
relationship is preferred by the majority of parsimony analyses, though
a small subset of weighting parameters places the craniiform clade
within the rhynchonelliforms instead.

The Bayesian results offer a more surprising interpretation that places
the craniiforms as paraphyletic with respect to all other brachiopods,
with \emph{Gasconsia} representing the basalmost member of the
Rhynchonellid lineage, upholding suggestions
\citep{Holmer2014OrdovicianSilurian} of a chileid rather than
trimerellid affinity. To our knowledge, the hypothesis of a paraphyletic
craniiform+trimerellid grade has never been proposed, and represents a
poor fit to stratigraphic data; potentially it represents an artefact
resulting from the incorrect handling of inapplicable data within the Mk
model.
\item[Rhynchonelliforms]
The position of kutorginids within the rhynchonelliform stem lineage has
been tricky to resolve \citep{Holmer2018Theattachment}; our results
agree that they form a clade, but differ on their closest relatives;
Fitch parsimony places them as sister to the Chileids; correcting for
inapplicables places them sister to Rhynchonelliforms; and Bayesian
analysis fails to distinguish between these two possibilities. These
results are broadly in accord with previous proposals
\citep{Holmer2018Evolutionarysignificance}. The protorthid
\emph{Glyptoria} is the earliest diverging of the included
rhynchonelliform lineages.

\emph{Salanygolina} has been interpreted as a stem-group
rhynchonelliform based on its combination of paterinid and chileate
features \citep{Holmer2009Theenigmatic}. Our results position
\emph{Salanygolina} as sister either to the Chileids or the Chileids +
Rhynchonelliforms, corroborating this interpretation.

Basal rhynchonellids are characterized by a circular umbonal perforation
in the ventral valve, associated with a colleplax. Partly on this basis,
the aberrant taxa \emph{Yuganotheca} and \emph{Tomteluva} tend to plot
close to the chileids under Fitch and Bayesian analysis, though a
variety of positions in this region of the tree are equally plausible.
The BGS method, in contrast, supports the interpretation of
\emph{Yuganotheca} as a stem-group brachiopod \citep{Zhang2014Anearly}.
\item[Linguliforms]
The reconstruction of Linguloformea comprising Linguloidea as sister to
Discinoidea is as expected. Lingulellotretids also sit within this
linguliform grouping; a position in the phoronid stem lineage
\citep[advocated by][]{Balthasar2009EarlyCambrian} is not upheld.
Acrotretids and Siphonotretids form a clade with \emph{Lingulosacculus}.

More novel is the reconstruction of the calcitic obolellid
\emph{Mummpikia} in the linguliform total group: a rhynchonelliform
affinity has been assumed based on its calcitic mineralogy. This said,
\citet{Balthasar2008iMummpikia} has highlighted the similarities between
obolellids and linguliform brachiopods, including sub-μm vertical canals
and the detailed configuration of the posterior shell margin. Our
analysis upholds the case for a linguliform affinity for
\emph{Mummpikia}; a calcitic shell seemingly arose through an
independent change within this taxon As such, \emph{Mummpikia} has no
direct bearing on the origin of `Calciata', save that shell mineralogy
is perhaps less static than commonly assumed.

More generally, our results identify Class Obolellata as polyphyletic:
\emph{Alisina} (Trematobolidae) plots within Rhynchonellata;
\emph{Tomteluva} is harder to place, but tends to group with
\emph{Salanygolina} stemwards of the chileids.
\item[Paterinids]
Paterinids have traditionally been placed within the Linguliforms on the
basis of their phosphatic shell \citep{Williams2007Supplement}, which we
identify as ancestral within the brachiopod crown group; consequently,
our analysis places the paterinids within the Rhynchonelliforms instead.
Characters supporting this position include the strophic hinge line,
planar cardinal area, the absence of a pedicle nerve impression, and the
morphology of the mantle canals.

More generally, although some lingulids can be found which share more
generic characters (e.g.~shell growth direction) with paterinids, the
particular combination of characters exhibited in paterinids does not
occur anywhere in the linguliform lineage, but is more similar to that
of basal rhynchonelliforms, particularly \emph{Salanygolina} \citep[as
noted by][]{Holmer2009Theenigmatic}.
\item[Tommotiids]
Tommotiids represent a basal grade, paraphyletic to phoronids and
crown-group brachiopods, in line with previous interpretations.

\emph{Mickwitzia} is consistently the most crownwards of the tommotiids,
falling as sister to the brachiopod crown group (except in the Bayesian
results, where they fall within the paraphyletic craniiform grade).
\emph{Mickwitzia} is closely related to \emph{Micrina} and
\emph{Heliomedusa}, though the exact nature of this relationship varies
from analysis to analysis. The latter affilitation reflects similarities
emphasized by Holmer and Popov in \citet{Williams2007Supplement}.

\emph{Dailyatia} tends to plot closely with \emph{Halkieria}, reflecting
the similarity in the form of their proposed scleritome
\citep{Skovsted2015Theearly}. Bayesian analysis recovers this pair as
sister to annelids and molluscs; Fitch parsimony places them in the
molluscan stem group. Inapplicable-corrected parsimony instead places
these taxa as sister to hyoliths + brachiopods \citep[cf.][]{Zhao2017}.
\item[Hyoliths]
Within the hyoliths, orthothecids are consistently recovered as a grade
that is paraphyletic to the hyolithids. Hyoliths as a whole are
interpreted as stem-group Brachiopods, which refines the broader
phylogenetic position proposed by \citet{Moysiuk2017Hyolithsare}. This
is to say, they sit closer to brachiopods than the phoronids do, but no
analysis places them within the Brachiopod crown group.

Tommotiids lie both stemwards (e.g. \emph{Eccentrotheca}) and crownwards
(\emph{Mickwitzia}) of hyoliths, which thus represent derived
tommotiids.
\end{description}

\hypertarget{figures}{\chapter*{Supplementary Figures}\label{figures}}
\addcontentsline{toc}{chapter}{Supplementary Figures}

\begin{center}\includegraphics[width=0.8\linewidth]{images/image1} \end{center}

\textbf{Fig. S1. \emph{Pedunculotheca diania} Sun, Zhao et Zhu gen. et
sp. nov. from the Chengjiang Biota, Yunnan Province, China.} (a) NIGPAS
166601, external mould of dorsum with dorsal apex and pedicle foramen.
(b) NIGPAS 166597, preserving conical shell, operculum and internal soft
tissue, showing a compressed elliptic cross-section; backscatter
electron micrograph of boxed region shown in (c). (d) NIGPAS 166599b,
counterpart, juvenile conical shell with operculum showing two
longitudinal ventral grooves and circular larval shell. (e) NIGPAS
166602, conical shell with incomplete attachment structure. (f) NIGPAS
166598, broken shell with two ventral furrows and incomplete attachment
structure. (g) NIGPAS 166596, incomplete shell with one medial ventral
furrow and short attachment structure with coelomic cavity; detail of
boxed region shown in (h). (i) NIGPAS 166603, exterior of operculum.
Scale bars: 2mm (for a, b and e--g); 500~µm (for c, h and i).

Abbreviations: an = anus, cc = coelomic cavity, da = dorsal apex, es =
esophagus, in = intestine, mo = mouth, pe = pedicle, st = stomach.

\clearpage

\begin{center}\includegraphics[width=0.8\linewidth]{images/image2} \end{center}

\textbf{Fig. S2. Elemental distribution in the gut of
\emph{Pedunculotheca diania} Sun, Zhao et Zhu gen. et sp. nov.} NIGPAS
166597. Region corresponds to boxed region in Fig. S1c. Scale bar =
100~µm.

Abbreviations: BE = backscatter electron image, O = Oxygen, Si =
Silicon, Al = Aluminium, Fe = Iron, C = Carbon.

\clearpage

\includegraphics{Brachiopod_phylogeny_files/figure-latex/brach-diversity-1.pdf}

\textbf{Fig. S3. Global diversity of brachiopods through the Paleozoic.}
Points represent number of genera reported in each time bin; lines
represent rolling mean diversity over three consecutive time bins. Data
from Paleobiology database.

\clearpage

\hypertarget{table}{\chapter*{Supplementary Table}\label{table}}
\addcontentsline{toc}{chapter}{Supplementary Table}

\begin{tabular}{l|l|l}
\hline
NIGPAS Specimen numbers & Fossil locality & Coordinates\\
\hline
166593, 166617 & Shankou Village, Anning & 24°49’53’’ N, 102°24’47.9” E\\
\hline
166594, 166595 & Yaoying Village, Wuding & 25°36’01.2” N, 102°20’04.6” E\\
\hline
166596--166616 & Ma'anshan Village, Chengjiang & 24°40’37.2” N, 102°58’40.2” E\\
\hline
\end{tabular}

\textbf{Table S1. Provenance of fossil material.} Individuals from the
Yaoying section are usually bigger, with a thicker body wall, and have a
smaller ratio of apertural width to shell length than specimens from
other areas. In the absence of other differentiating features, we
consider these deviations to represent ecophenotypical variation within
a single species, perhaps reflecting the increased energetics and
predation pressure that accompany the shallower water depth reported at
the Yaoying section \citep{Zhao2012}.

\clearpage

\bibliography{References.bib}


\end{document}
